name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - feature/Web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./src/Web
        run: npm install

      - name: Build Storybook
        working-directory: ./src/Web
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: feature/Web
          FOLDER: src/Web/storybook-static
